# Generated by Django 5.2 on 2025-07-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodigoIdentificador",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_permiso", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado_Permiso", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rol", models.CharField(max_length=50, unique=True)),
                ("estado_Rol", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                ("telefono", models.CharField(max_length=50, unique=True)),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("ci", models.CharField(max_length=20, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("estado_Usuario", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClasificacionDerecho",
            fields=[
                (
                    "codigo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.codigoidentificador",
                    ),
                ),
                ("notario_juez", models.CharField(max_length=200)),
                ("nombre_notario_juez", models.CharField(max_length=200)),
                ("fecha_inscripcion", models.DateField(blank=True, null=True)),
                (
                    "matricula_partida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "numero_testimonio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_testimonio", models.DateField(blank=True, null=True)),
                ("superficie", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="CodigoCatastral",
            fields=[
                (
                    "codigo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.codigoidentificador",
                    ),
                ),
                ("Distrito", models.CharField(blank=True, max_length=100, null=True)),
                ("Sector", models.CharField(blank=True, max_length=100, null=True)),
                ("Manzano", models.CharField(blank=True, max_length=100, null=True)),
                ("Predio", models.CharField(blank=True, max_length=100, null=True)),
                ("SubPredio", models.CharField(blank=True, max_length=100, null=True)),
                ("Direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("Zona", models.CharField(blank=True, max_length=100, null=True)),
                ("ViasDe", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "codigo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.codigoidentificador",
                    ),
                ),
                ("numero_inmueble", models.IntegerField(max_length=10)),
                ("padron_municipal", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ObraGruesa",
            fields=[
                (
                    "codigo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.codigoidentificador",
                    ),
                ),
                (
                    "b1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "b2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "b3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "b4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "b5",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Propietario",
            fields=[
                (
                    "codigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.codigoidentificador",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolesPermisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.permisos"
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.roles"
                    ),
                ),
            ],
            options={
                "unique_together": {("rol", "permiso")},
            },
        ),
        migrations.CreateModel(
            name="UsuariosRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.roles"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuarios"
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "rol")},
            },
        ),
    ]
