# Generated by Django 5.2 on 2025-07-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentificadorInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador_catastral_id",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "identificador_propietario_id",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "inmueble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identificadores",
                        to="users.inmueble",
                    ),
                ),
            ],
        ),
    ]
